using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// Use for managing most of the implemented systems within SIDI
public class Manager : MonoBehaviour 
{
    public List<Information> informationlist;
    public float overallcorrectness;
    public int numberOfInfo = 3;
    public bool running = false;

    void Awake()
    {
        informationlist = new List<Information>();
        GameObject.Find("InfoNum").GetComponent<Text>().text = numberOfInfo.ToString();
    }

    // Creates and then stores the master copy of all of the information for the demo.
    // In an actual game much of this would be generated by events in the game world.
    public void GenerateInfo()
    {
        for (uint i = 0; i < numberOfInfo; i++)
        {
            Information info = new Information();
            info.Generate(i, true, Random.Range(0.1f, 100.0f), Random.Range(1, 10), new List<int> { Random.Range(1, 500), Random.Range(1, 500), Random.Range(1, 500), Random.Range(1, 500) });
            informationlist.Add(info);
        }
        running = true;
    }

    // Setter
    public void setInfo(float info)
    {
        numberOfInfo = Mathf.FloorToInt(info);
        GameObject.Find("InfoNum").GetComponent<Text>().text = numberOfInfo.ToString();
    }

    // Button Controls
    public void Restart()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
    public void Quit()
    {
        Application.Quit();
    }
}